"""
Simulated-inbox demo mode — 10 pre-scripted emails with pre-computed verdicts.
Emails arrive one at a time at the intervals defined by DEMO_ARRIVAL_TIMES.
"""

# Cumulative seconds from Play to when each email should appear.
# Gaps feel natural (3–11 s) and the full run lasts ~72 s.
DEMO_ARRIVAL_TIMES = [3, 7, 11, 16, 21, 27, 33, 39, 45, 52]

# received is intentionally blank — app.py fills it with the live clock when delivered.
DEMO_EMAILS = [
    # ── 1 · Safe ─────────────────────────────────────────────────────────────
    {
        "id": "demo-001",
        "folder": "Inbox",
        "sender": "Alex Chen",
        "sender_email": "alex.chen@techcorp.com",
        "recipient": "taylor@luman-demo.com",
        "subject": "Coffee catch-up this week?",
        "preview": "Happy to reconnect — are you free Thursday afternoon?",
        "received": "",
        "status": "Safe",
        "confidence_band": "high",
        "confidence_pct": 96,
        "top_reasons": [
            "Sender address matches a known colleague on a trusted company domain.",
            "The message is informal and makes no request for sensitive information.",
            "No links, attachments, or calls to take urgent action.",
        ],
        "recommended_actions": [
            "No action required — reply normally if you would like to meet.",
            "If you do not recognize this sender, confirm through your company directory.",
        ],
        "explanation": "This looks like a genuine personal note from a colleague. Nothing suspicious.",
        "body": [
            "Hey Taylor,",
            "Hope your week is going well! I've been meaning to catch up — we haven't connected since the all-hands in January.",
            "Are you free Thursday afternoon? Even a 20-minute coffee would be great.",
            "Let me know,",
            "Alex",
        ],
        "simulated_link": "",
        "technical_signals": {
            "urgency": False, "credential_request": False,
            "domain_mismatch": False, "shortened_link": False,
        },
    },
    # ── 2 · Likely Phishing ──────────────────────────────────────────────────
    {
        "id": "demo-002",
        "folder": "Inbox",
        "sender": "PayPal Support",
        "sender_email": "security@paypal-accounts-verify.xyz",
        "recipient": "taylor@luman-demo.com",
        "subject": "Your PayPal account has been limited — action required",
        "preview": "Unusual sign-in activity detected. Verify your identity within 24 hours.",
        "received": "",
        "status": "Likely Phishing",
        "confidence_band": "high",
        "confidence_pct": 96,
        "top_reasons": [
            "The sender domain is not paypal.com — it is a lookalike designed to deceive.",
            "A 24-hour deadline is engineered to pressure you into acting without thinking.",
            "You are being asked to verify account credentials through a link in this message.",
        ],
        "recommended_actions": [
            "Do not click any links in this message.",
            "Go directly to paypal.com in your browser to check your account status.",
            "Report this email to phishing@paypal.com.",
            "If you already clicked a link, change your PayPal password immediately.",
        ],
        "explanation": "This is a credential phishing attack impersonating PayPal. The domain is fake and the urgency is designed to bypass your judgement.",
        "body": [
            "Dear Customer,",
            "We have detected unusual sign-in activity on your PayPal account from an unrecognized device. To protect your funds, we have temporarily limited your access.",
            "You must verify your identity within 24 hours to restore full account access. Failure to verify will result in permanent account suspension.",
            "Click below to secure your account now:",
            "https://paypal-accounts-verify.xyz/secure-login",
            "PayPal Security Team",
        ],
        "simulated_link": "paypal-accounts-verify.xyz/secure-login",
        "technical_signals": {
            "urgency": True, "credential_request": True,
            "domain_mismatch": True, "shortened_link": False,
        },
    },
    # ── 3 · Safe ─────────────────────────────────────────────────────────────
    {
        "id": "demo-003",
        "folder": "Inbox",
        "sender": "IT Help Desk",
        "sender_email": "helpdesk@techcorp.com",
        "recipient": "taylor@luman-demo.com",
        "subject": "Scheduled maintenance window — Sunday 2:00–4:00 AM",
        "preview": "No action required. Services will be briefly unavailable during this window.",
        "received": "",
        "status": "Safe",
        "confidence_band": "high",
        "confidence_pct": 95,
        "top_reasons": [
            "The sender is your company IT team on a recognized internal domain.",
            "The message is purely informational — no action, login, or payment is requested.",
            "Maintenance notifications are a routine and expected IT communication.",
        ],
        "recommended_actions": [
            "No action required.",
            "Save any open work before Sunday at 2:00 AM to avoid losing it.",
            "Contact helpdesk@techcorp.com if you have questions after the window.",
        ],
        "explanation": "This is a routine IT maintenance announcement. It asks nothing of you and comes from a trusted internal address.",
        "body": [
            "Hi everyone,",
            "We will be performing scheduled maintenance on our internal systems this Sunday from 2:00 AM to 4:00 AM. During this window, email, VPN, and the employee portal will be temporarily unavailable.",
            "No action is required from you. Please save any work in progress before the window begins.",
            "Thank you,",
            "IT Help Desk",
        ],
        "simulated_link": "",
        "technical_signals": {
            "urgency": False, "credential_request": False,
            "domain_mismatch": False, "shortened_link": False,
        },
    },
    # ── 4 · Needs Review ─────────────────────────────────────────────────────
    {
        "id": "demo-004",
        "folder": "Inbox",
        "sender": "Netflix Billing",
        "sender_email": "billing@netflix-support.info",
        "recipient": "taylor@luman-demo.com",
        "subject": "Update your payment method to avoid service interruption",
        "preview": "We couldn't process your latest payment. Update your billing info to stay subscribed.",
        "received": "",
        "status": "Needs Review",
        "confidence_band": "medium",
        "confidence_pct": 74,
        "top_reasons": [
            "The sender domain is netflix-support.info, not netflix.com — a common impersonation pattern.",
            "The message asks you to update financial details through a link.",
            "Netflix-themed billing notices are among the most frequently faked email templates.",
        ],
        "recommended_actions": [
            "Do not click the link in this message.",
            "Log in to netflix.com directly from your browser to check your billing status.",
            "If your payment actually failed, update it only through the official Netflix site.",
            "Report this message if you confirm it is not from Netflix.",
        ],
        "explanation": "This message may be real, but the sender domain does not match Netflix's official address. Always verify billing issues through the official site.",
        "body": [
            "Hi Taylor,",
            "We were unable to process your payment for this billing period. To avoid an interruption to your service, please update your payment information as soon as possible.",
            "Update payment: https://netflix-support.info/update-billing",
            "If you recently updated your payment method, allow up to 24 hours for changes to take effect.",
            "The Netflix Team",
        ],
        "simulated_link": "netflix-support.info/update-billing",
        "technical_signals": {
            "urgency": True, "credential_request": True,
            "domain_mismatch": True, "shortened_link": False,
        },
    },
    # ── 5 · Likely Phishing ──────────────────────────────────────────────────
    {
        "id": "demo-005",
        "folder": "Inbox",
        "sender": "IRS Tax Center",
        "sender_email": "refunds@irs-refund-portal.top",
        "recipient": "taylor@luman-demo.com",
        "subject": "Your federal tax refund of $1,847.00 is ready to claim",
        "preview": "Verify your identity to receive your refund before the 7-day expiration.",
        "received": "",
        "status": "Likely Phishing",
        "confidence_band": "high",
        "confidence_pct": 98,
        "top_reasons": [
            "The IRS never contacts taxpayers by email — all official correspondence is by postal mail.",
            "The domain is not irs.gov and uses a suspicious .top extension associated with scams.",
            "Promising a specific refund amount with a 7-day expiration is a classic social engineering tactic.",
        ],
        "recommended_actions": [
            "Do not click any links or respond to this message.",
            "The IRS does not send refund notices by email — this is an identity theft attempt.",
            "Report this email to phishing@irs.gov.",
            "If you entered any personal information, file a report at identitytheft.gov.",
        ],
        "explanation": "This is an IRS impersonation scam. The real IRS does not communicate refunds by email, and the domain is not irs.gov.",
        "body": [
            "NOTICE FROM THE INTERNAL REVENUE SERVICE",
            "Our records show you are eligible to receive a federal tax refund of $1,847.00 for the most recent tax year.",
            "To claim your refund, you must verify your identity within 7 days. After this period, the refund will be returned to the federal treasury.",
            "Verify your identity here: https://irs-refund-portal.top/claim",
            "Internal Revenue Service",
        ],
        "simulated_link": "irs-refund-portal.top/claim",
        "technical_signals": {
            "urgency": True, "credential_request": True,
            "domain_mismatch": True, "shortened_link": False,
        },
    },
    # ── 6 · Safe ─────────────────────────────────────────────────────────────
    {
        "id": "demo-006",
        "folder": "Inbox",
        "sender": "Maria Santos",
        "sender_email": "m.santos@techcorp.com",
        "recipient": "taylor@luman-demo.com",
        "subject": "Re: Q2 planning — notes from today's call",
        "preview": "Summarizing the action items we agreed on. Let me know if I missed anything.",
        "received": "",
        "status": "Safe",
        "confidence_band": "high",
        "confidence_pct": 97,
        "top_reasons": [
            "Sent from a recognized colleague on a trusted company domain.",
            "The message is a direct reply to an existing thread — not unsolicited contact.",
            "No links, attachments, or requests for sensitive information.",
        ],
        "recommended_actions": [
            "No action required — reply or follow up on the listed action items as needed.",
        ],
        "explanation": "This is a normal work follow-up from a known colleague. Nothing unusual.",
        "body": [
            "Hi Taylor,",
            "Thanks for a productive call today. Here is my summary of the key action items:",
            "1. Taylor to finalize the Q2 budget estimate by Wednesday\n2. Maria to schedule the stakeholder review for the week of the 15th\n3. Both to review the draft roadmap before the next sync",
            "Let me know if I missed anything or if the timeline needs adjusting.",
            "Thanks,\nMaria",
        ],
        "simulated_link": "",
        "technical_signals": {
            "urgency": False, "credential_request": False,
            "domain_mismatch": False, "shortened_link": False,
        },
    },
    # ── 7 · Needs Review ─────────────────────────────────────────────────────
    {
        "id": "demo-007",
        "folder": "Inbox",
        "sender": "Amazon Shipping",
        "sender_email": "tracking@amazon-orders-update.co",
        "recipient": "taylor@luman-demo.com",
        "subject": "Your package has shipped — estimated arrival: Friday",
        "preview": "Your recent order is on its way. Track your delivery below.",
        "received": "",
        "status": "Needs Review",
        "confidence_band": "medium",
        "confidence_pct": 68,
        "top_reasons": [
            "The sender domain is amazon-orders-update.co, not amazon.com.",
            "Amazon shipping notifications are among the most widely cloned phishing templates.",
            "The tracking link leads to an unverified third-party domain.",
        ],
        "recommended_actions": [
            "Do not click the tracking link in this message.",
            "Go directly to amazon.com and check Your Orders to track your package.",
            "If you were not expecting an Amazon delivery, disregard this message.",
        ],
        "explanation": "This could be a legitimate notification, but the sender domain does not match Amazon. Always check order status directly on amazon.com.",
        "body": [
            "Hello Taylor,",
            "Your recent order has shipped and is on its way to you. Estimated delivery is this Friday.",
            "Track your package: https://amazon-orders-update.co/track?id=TBA-49182736",
            "If you have questions about your order, visit the Help Center on amazon.com.",
            "Amazon Customer Service",
        ],
        "simulated_link": "amazon-orders-update.co/track",
        "technical_signals": {
            "urgency": False, "credential_request": False,
            "domain_mismatch": True, "shortened_link": False,
        },
    },
    # ── 8 · Likely Phishing ──────────────────────────────────────────────────
    {
        "id": "demo-008",
        "folder": "Inbox",
        "sender": "Chase Bank Security",
        "sender_email": "alerts@chase-secure-login.ml",
        "recipient": "taylor@luman-demo.com",
        "subject": "URGENT: Suspicious transaction detected on your account",
        "preview": "A $2,340 transaction was flagged. Verify immediately to prevent unauthorized access.",
        "received": "",
        "status": "Likely Phishing",
        "confidence_band": "high",
        "confidence_pct": 97,
        "top_reasons": [
            "The sender domain is not chase.com — it uses the .ml extension associated with malicious sites.",
            "An invented large transaction is used to create panic and push you to act without thinking.",
            "You are asked to log in and verify account credentials through an email link.",
        ],
        "recommended_actions": [
            "Do not click any links in this message.",
            "Call the number on the back of your Chase card or visit chase.com directly.",
            "Report this email to abuse@chase.com.",
            "If you entered any credentials, call Chase fraud at 1-800-935-9935 immediately.",
        ],
        "explanation": "This is a bank phishing attack. Chase will never ask you to verify your account through an email link. The large invented transaction is designed to cause panic.",
        "body": [
            "CHASE BANK SECURITY ALERT",
            "We have detected a suspicious transaction on your account:",
            "Transaction: $2,340.00 · Merchant: International Wire · Status: PENDING",
            "If you did not authorize this transaction, verify your identity immediately to block it. Delays may result in the funds being released.",
            "Verify your account: https://chase-secure-login.ml/verify",
            "Chase Security Team",
        ],
        "simulated_link": "chase-secure-login.ml/verify",
        "technical_signals": {
            "urgency": True, "credential_request": True,
            "domain_mismatch": True, "shortened_link": False,
        },
    },
    # ── 9 · Safe ─────────────────────────────────────────────────────────────
    {
        "id": "demo-009",
        "folder": "Inbox",
        "sender": "HR Benefits Team",
        "sender_email": "benefits@techcorp.com",
        "recipient": "taylor@luman-demo.com",
        "subject": "Open enrollment closes Friday — review your benefit selections",
        "preview": "Reminder: benefits open enrollment closes this Friday at 5 PM.",
        "received": "",
        "status": "Safe",
        "confidence_band": "high",
        "confidence_pct": 93,
        "top_reasons": [
            "The sender is your company HR team using a recognized internal domain.",
            "Annual benefits enrollment is a routine and expected HR communication.",
            "The message directs you to an internal portal — not an unverified external link.",
        ],
        "recommended_actions": [
            "Log in to the employee portal through your usual bookmark or company intranet.",
            "Review and confirm your benefit elections before Friday at 5 PM.",
            "Contact benefits@techcorp.com with any questions.",
        ],
        "explanation": "This is a legitimate internal HR reminder. Benefits enrollment emails from company HR are expected and safe.",
        "body": [
            "Hi Taylor,",
            "This is a reminder that the annual benefits open enrollment window closes this Friday at 5:00 PM.",
            "If you do not make changes, your current selections will carry over automatically. However, we recommend logging in to review your options — there are two new plan choices available this year.",
            "Questions? Contact the Benefits Team at benefits@techcorp.com.",
            "HR Benefits Team",
        ],
        "simulated_link": "",
        "technical_signals": {
            "urgency": False, "credential_request": False,
            "domain_mismatch": False, "shortened_link": False,
        },
    },
    # ── 10 · Needs Review ────────────────────────────────────────────────────
    {
        "id": "demo-010",
        "folder": "Inbox",
        "sender": "FedEx Delivery",
        "sender_email": "delivery@fedex-tracking-update.click",
        "recipient": "taylor@luman-demo.com",
        "subject": "Delivery attempt failed — reschedule to avoid return to sender",
        "preview": "We attempted delivery but no one was available. Reschedule within 3 days.",
        "received": "",
        "status": "Needs Review",
        "confidence_band": "medium",
        "confidence_pct": 72,
        "top_reasons": [
            "The sender domain is fedex-tracking-update.click, not fedex.com.",
            "Missed delivery notices with a rescheduling link are a high-frequency phishing template.",
            "A 3-day deadline creates mild urgency to push action before verification.",
        ],
        "recommended_actions": [
            "Do not click the reschedule link in this message.",
            "Go directly to fedex.com and use your tracking number to check delivery status.",
            "If you are not expecting a FedEx package, disregard this message.",
        ],
        "explanation": "This may be a real delivery notice, but the domain does not belong to FedEx. Always verify missed delivery notices at fedex.com.",
        "body": [
            "Hello,",
            "We attempted to deliver your FedEx package today but were unable to complete the delivery — no one was available at the address on file.",
            "Please reschedule your delivery within 3 business days to avoid the package being returned to the sender:",
            "Reschedule: https://fedex-tracking-update.click/reschedule?id=794-661-20948",
            "FedEx Customer Support",
        ],
        "simulated_link": "fedex-tracking-update.click/reschedule",
        "technical_signals": {
            "urgency": True, "credential_request": False,
            "domain_mismatch": True, "shortened_link": False,
        },
    },
]
